name: Build APK
on: [push]
jobs:
  build-android:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Accept Android licenses
        run: |
          yes | sdkmanager --licenses || true

      - name: Build APK
        run: |
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-calculator-apk
          path: bin/*.apk
